# Generated by Django 4.2.1 on 2023-06-06 07:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='consume',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
