# Generated by Django 4.2.1 on 2023-06-06 23:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0003_consume_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consume',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 6, 23, 23, 0, 403079, tzinfo=datetime.timezone.utc)),
        ),
    ]
