# Generated by Django 4.2.1 on 2023-06-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0005_alter_consume_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='consume',
            name='quantity',
            field=models.IntegerField(default=100),
        ),
    ]
